### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by YouCanNotBeSerious** [Bunn/TempGlance#2]
Hi - no issue to open, just a thank you.  

The binary would not run for me so i grabbed the source, fought with certificate signing for a bit, and now have successfully built TemperatureGlance and it's exactly the small simple app i wanted for my menubar :-)

I have no understanding of the code, i am a (beginner) embedded C and python type guy, but also have no need to change anything.

Thanks for providing this for free!

**Comment by YouCanNotBeSerious** [comment]
Well isn't that just the way..... after (i believe) an OS update, the app i built doesn't run any more!  I just get "this app can not be opened" - I don't posess your skills and am surprised I actually got xcode to build it in the first place, and now it complains again about certificates. I think I may have build some sort of temporary test app and it is invalid after either a reboot or the OS update....

Anyway, is there a chance you would mind building a version of this that will run on my M2 macbook?  I just can not find any other app that is this simple and is one click to see all my home temperatures!

**Comment by Bunn** [comment]
@YouCanNotBeSerious it is getting increasingly hard to find time for my side projects, but I'll give a try during this next weekend and I'll post my findings here (hopefully with a working build 😅)

Could you just let me know which macOS version are you using? Thanks

**Comment by YouCanNotBeSerious** [comment]
> @YouCanNotBeSerious it is getting increasingly hard to find time for my side projects, but I'll give a try during this next weekend and I'll post my findings here (hopefully with a working build 😅)
> 
> Could you just let me know which macOS version are you using? Thanks

Hello !

13.4.1 (22F82) on a M2 MacBook AIr, 2022.  From what I know, and again I'm for sure not an application coder, a beginner embedded guy maybe - surely a universal binary can be made?

I realize I am asking for something that takes work from yourself, and I benefit from, so apart form calling on your good nature I am happy to help if I can: I have Xcode on my machine, i can and have opened your project and tried to build, at the moment i am again fighting certificate signing of bundles, but if you want me to run or build something on an M2 machine that might help with getting a version that other apple silicon users can run I will be all for it!

Thanks.

**Comment by Bunn** [comment]
Try this version: https://github.com/Bunn/TempGlance/releases/tag/1.1

I can't sign the build so you need to open with "right click -> open" from finder, and make sure you can run unsigned apps, I keep getting an issue with homekit capabilities on catalyst and I currently don't have time to look deeper into it.

**Comment by YouCanNotBeSerious** [comment]
I have been reading up on using "console" to get more details on error messages, here's what i get - it's talking about provisioning profiles and not being allowed.

When you say to make sure i can run unsigned app, i take it you mean the settings>privacy>allow applications from ..... ?  I only have the options "app store" or "app store and identified developers" and the second is ticked. 

Cheers



default	10:34:35.835933+1200	runningboardd	Creating and launching job for: app<application.dev.bunn.temperatureglance.263563.263588(501)>
default	10:34:35.836096+1200	runningboardd	_mutateContextIfNeeded called for dev.bunn.temperatureglance
default	10:34:35.836493+1200	runningboardd	app<application.dev.bunn.temperatureglance.263563.263588(501)>: -[RBPersonaManager personaForIdentity:context:personaUID:personaUniqueString:] required 0.000000 ms (wallclock); resolved to {4294967295, (null)}
default	10:34:35.836693+1200	runningboardd	'app<application.dev.bunn.temperatureglance.263563.263588(501)>' Constructed job description (context <RBSLaunchContext: 0x14e9147e0>):
<dictionary: 0x14d728dd0> { count = 22, transaction: 0, voucher = 0x0, contents =
	"Platform" => <int64: 0x84ad1f95c99908bf>: 6
	"ProcessType" => <string: 0x14e8a2a70> { length = 3, contents = "App" }
	"EnableTransactions" => <bool: 0x1f30f83f0>: false
	"_ManagedBy" => <string: 0x14e8d8e20> { length = 22, contents = "com.apple.runningboard" }
	"CFBundleIdentifier" => <string: 0x14e8341e0> { length = 26, contents = "dev.bunn.temperatureglance" }
	"_ResourceCoalition" => <string: 0x14e8cd7d0> { length = 62, contents = "app<application.dev.bunn.temperatureglance.263563.263588(501)>" }
	"_DisablePointerAuth" => <bool: 0x1f30f83d0>: true
	"ThrottleInterval" => <int64: 0x84ad1f963666f777>: 2147483647
	"MachServices" => <dictionary: 0x14e813a30> { count = 0, transaction: 0, voucher = 0x0, contents =
	}
	"EnablePressuredExit" => <bool: 0x1f30f83f0>: false
	"LimitLoadToSessionType" => <array: 0x14e8ce900<…>
default	10:34:35.911217+1200	taskgated-helper	Provisioning Profile Validation: profile 'B2RUA6XMHC.dev.bunn.temperatureglance' is not provisioned for this device (<private>)
error	10:34:35.911359+1200	taskgated-helper	embedded provisioning profile not valid: file:///Volumes/shared/TemperatureGlance.app/Contents/embedded.provisionprofile error: Error Domain=CPProfileManager Code=-212 "Provisioning profile does not allow this device." UserInfo={NSLocalizedDescription=Provisioning profile does not allow this device.}
error	10:34:35.914307+1200	taskgated-helper	Disallowing dev.bunn.temperatureglance because no eligible provisioning profiles found
default	10:34:35.914999+1200	amfid	/Volumes/shared/TemperatureGlance.app/Contents/MacOS/TemperatureGlance not valid: Error Domain=AppleMobileFileIntegrityError Code=-413 "No matching profile found" UserInfo={NSURL=file:///Volumes/shared/TemperatureGlance.app/, NSLocalizedDescription=No matching profile found}
error	10:34:35.916001+1200	runningboardd	<OSLaunchdJob | handle=3276E18F-5CCA-4A6B-A7A3-0D07CC25A7FE>: job failed to spawn, plist={
	Platform => 6
	ProcessType => App
	EnableTransactions => false
	_ManagedBy => com.apple.runningboard
	CFBundleIdentifier => dev.bunn.temperatureglance
	_ResourceCoalition => app<application.dev.bunn.temperatureglance.263563.263588(501)>
	_DisablePointerAuth => true
	ThrottleInterval => 2147483647
	MachServices => {
	}
	EnablePressuredExit => false
	LimitLoadToSessionType => [<capacity = 8>
		0: Aqua
		1: LoginWindow
	]
	InitialTaskRole => 2
	EnvironmentVariables => {
		__CF_USER_TEXT_ENCODING => 0x1F5:0:15
		TMPDIR => /var/folders/qp/j4ztqsh96rjd_1hdb6bb0b200000gn/T/
		SHELL => /bin/zsh
		HOME => /Users/allun
		SSH_AUTH_SOCK => /private/tmp/com.apple.launchd.1V9YEo8kXS/Listeners
		LOGNAME => allun
		PATH => /usr/bin:/bin:/usr/sbin:/sbin
		XPC_SERVICE_NAME => com.apple.Finder
		__CFBundleIdentifier => dev.bunn.temperatureglance
		COMMAND_MODE => unix2003
		USER => allun
		XPC_FLAGS => 0x0
	}
	_AdditionalProperties => {
		RunningBoar<…>
default	10:34:35.915138+1200	kernel	mac_vnode_check_signature: /Volumes/shared/TemperatureGlance.app/Contents/MacOS/TemperatureGlance: code signature validation failed fatally: When validating /Volumes/shared/TemperatureGlance.app/Contents/MacOS/TemperatureGlance:
  Code has restricted entitlements, but the validation of its code signature failed.
Unsatisfied Entitlements:
default	10:34:35.916321+1200	runningboardd	Invalidating assertion 570-27966-369990 (target:app<application.dev.bunn.temperatureglance.263563.263588(501)>) from originator [osservice<com.apple.Finder(501)>:27966]
error	10:34:35.916687+1200	Finder	LAUNCH: RBSLaunchRequest FAILURE <private> dev.bunn.temperatureglance <private> 0x0-0x1a60a5f failed with error Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x6000022b2100 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}
error	10:34:35.916723+1200	Finder	LAUNCH: Runningboard launch of dev.bunn.temperatureglance <private> returned RBSRequestErrorFailed, error Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x6000022b2100 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}, so returning -10810
error	10:34:35.916809+1200	Finder	LAUNCH: request execute thru runningboard of 0x0-0x1a60a5f dev.bunn.temperatureglance/<private> failed with error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x6000022b2100 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}
default	10:34:35.915159+1200	kernel	proc 89560: load code signature error 4 for file "TemperatureGlance"

**Comment by YouCanNotBeSerious** [comment]
Google tells me - build with "app sandbox" turned off?  Or with "debug build" ?  Seems to be it's allowed to run on the machine that built it but not others?  This makes me wonder if the original issue was not the apple silicon vs intel but this permissions thing...

https://developer.apple.com/forums/thread/128121

**Comment by Bunn** [comment]
>  Provisioning Profile Validation: profile 'B2RUA6XMHC.dev.bunn.temperatureglance' is not provisioned for this device ()

Yeah, I can't sign as distribution because catalyst (macOS) doesn't have access to homekit capabilities and building with my dev profile doesn't allow it to be ran in other computers. I've read [here](https://developer.apple.com/forums/thread/661941) that if this is distributed thru the App Store it might work.

Important to note is that these findings are based on real quick searches, I might investigate it further once/if I manage to find more time to work on this app, until then (and I know it's not an ideal answer) If you create a developer account and build it for yourself it should work.

**Comment by YouCanNotBeSerious** [comment]
Makes sense, I am going to try the developer account/build it myself thing from fresh with some tutorials :-)

Thanks again though, it;s just such a perfect little app for what I want and I'm sure others would find it useful - I have looked at many many temperature in the menubar apps and they are all overcomplicated, i just want to click and see all my temps, nothing more !

Cheers

**Comment by Bunn** [comment]
Cool, I'm going to close this issue for now, sorry I couldn't be more helpful, hopefully I find some spare time to invest in a distribution channel for this app :)
